
# Triggers on PR into main
on:
  pull_request:
    branches:
      - main

jobs:
  # Validate all .html files
  HTML-validate:
      name: Validate all .html files
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install htmlhint w3c-html-validator

      - name: Run HTMLHint
        run: npx htmlhint '**/*.html'

      - name: Run W3C Validator
        run: npx w3c-html-validator '**/*.html'
  
  # Validate all .js files
  JavaScript-linter:
    name: Validate all .js files
    runs-on: ubuntu-latest
    needs: HTML-validate
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        run: |
          npm install eslint@8.10.0

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: npx eslint .
          --config .eslintrc.js
          --ext .js,.jsx,.ts,.tsx
        continue-on-error: false
